// Generated by CIRCT firtool-1.62.1
module GPI(
  input         clock,
                reset,
  input  [4:0]  slot_io_address,
  output [31:0] slot_io_rd_data,
  input  [31:0] slot_io_wr_data,
  input         slot_io_read,
                slot_io_write,
                slot_io_cs,
  input  [15:0] io_data_in
);

  reg [31:0] buf_in;
  always @(posedge clock) begin
    if (reset)
      buf_in <= 32'h0;
    else
      buf_in <= {16'h0, io_data_in};
  end // always @(posedge)
  assign slot_io_rd_data = buf_in;
endmodule

