// Generated by CIRCT firtool-1.62.1
module mcs_bridge(
  input  [31:0] io_io_address,
  input         io_io_addr_strobe,
  input  [31:0] io_io_write_data,
  input         io_io_write_strobe,
  input  [3:0]  io_io_byte_enable,
  output [31:0] io_io_read_data,
  input         io_io_read_strobe,
  output        io_fp_video_cs,
                io_fp_mmio_cs,
                io_fp_wr,
                io_fp_rd,
  output [20:0] io_fp_addr,
  output [31:0] io_fp_wr_data,
  input  [31:0] io_fp_rd_data
);

  wire mcs_bridge_enable = io_io_address[31:24] == 8'hC0;
  assign io_io_read_data = io_fp_rd_data;
  assign io_fp_video_cs = mcs_bridge_enable & io_io_address[23];
  assign io_fp_mmio_cs = mcs_bridge_enable & ~(io_io_address[23]);
  assign io_fp_wr = io_io_write_strobe;
  assign io_fp_rd = io_io_read_strobe;
  assign io_fp_addr = io_io_address[22:2];
  assign io_fp_wr_data = io_io_write_data;
endmodule

