// Generated by CIRCT firtool-1.62.1
module mmio_controller(
  input               io_fp_video_cs,
                      io_fp_mmio_cs,
                      io_fp_write,
                      io_fp_read,
  input  [20:0]       io_fp_addr,
  input  [31:0]       io_fp_wr_data,
  output [31:0]       io_fp_rd_data,
  output [63:0]       io_slot_cs,
  output [63:0][4:0]  io_slot_reg_addr,
  output [63:0][31:0] io_slot_write_data,
  output [63:0]       io_slot_write,
  input  [63:0][31:0] io_slot_read_data,
  output [63:0]       io_slot_read
);

  assign io_fp_rd_data = io_fp_read ? io_slot_read_data[io_fp_addr[10:5]] : 32'h0;
  assign io_slot_cs = io_fp_mmio_cs ? 64'h1 << io_fp_addr[10:5] : 64'h0;
  assign io_slot_reg_addr = {64{io_fp_addr[4:0]}};
  assign io_slot_write_data = {64{io_fp_wr_data}};
  assign io_slot_write = {64{io_fp_write}};
  assign io_slot_read = {64{io_fp_read}};
endmodule

