// Generated by CIRCT firtool-1.62.1
module mmio_controller(
  input               io_mmio_cs,
  input  [20:0]       io_mmio_address,
  input  [31:0]       io_mmio_write_data,
  input               io_mmio_write,
  output [31:0]       io_mmio_read_data,
  input               io_mmio_read,
  output [63:0]       io_slot_cs,
  output [63:0][4:0]  io_slot_reg_addr,
  output [63:0][31:0] io_slot_write_data,
  output [63:0]       io_slot_write,
  input  [63:0][31:0] io_slot_read_data,
  output [63:0]       io_slot_read
);

  assign io_mmio_read_data =
    io_mmio_read ? io_slot_read_data[io_mmio_address[10:5]] : 32'h0;
  assign io_slot_cs = io_mmio_cs ? 64'h1 << io_mmio_address[10:5] : 64'h0;
  assign io_slot_reg_addr = {64{io_mmio_address[4:0]}};
  assign io_slot_write_data = {64{io_mmio_write_data}};
  assign io_slot_write = {64{io_mmio_write}};
  assign io_slot_read = {64{io_mmio_read}};
endmodule

