// Generated by CIRCT firtool-1.62.1
module mmio_subsystem(
  input         clock,
                reset,
                io_fp_video_cs,
                io_fp_mmio_cs,
                io_fp_write,
                io_fp_read,
  input  [20:0] io_fp_addr,
  input  [31:0] io_fp_wr_data,
  output [31:0] io_fp_rd_data,
  input  [15:0] io_data_in,
  output [15:0] io_data_out,
  output [7:0]  io_anode_assert,
  output [6:0]  io_segs
);

  wire [31:0]       _sevenSegDisplay_slot_io_rd_data;
  wire struct packed {logic [7:0] anode_select; logic [6:0] segs; } _sevenSegDisplay_io;
  wire [31:0]       _timer_slot_io_rd_data;
  wire [31:0]       _gpi_slot_io_rd_data;
  wire [31:0]       _gpo_slot_io_rd_data;
  wire struct packed {logic [15:0] data_out; } _gpo_io;
  wire [63:0]       _mmioController_io_slot_cs;
  wire [63:0][4:0]  _mmioController_io_slot_reg_addr;
  wire [63:0][31:0] _mmioController_io_slot_write_data;
  wire [63:0]       _mmioController_io_slot_write;
  wire [63:0]       _mmioController_io_slot_read;
  mmio_controller mmioController (
    .io_fp_video_cs     (io_fp_video_cs),
    .io_fp_mmio_cs      (io_fp_mmio_cs),
    .io_fp_write        (io_fp_write),
    .io_fp_read         (io_fp_read),
    .io_fp_addr         (io_fp_addr),
    .io_fp_wr_data      (io_fp_wr_data),
    .io_fp_rd_data      (io_fp_rd_data),
    .io_slot_cs         (_mmioController_io_slot_cs),
    .io_slot_reg_addr   (_mmioController_io_slot_reg_addr),
    .io_slot_write_data (_mmioController_io_slot_write_data),
    .io_slot_write      (_mmioController_io_slot_write),
    .io_slot_read_data
      ({{32'hFFFFFFFF},
        {32'hFFFFFFFF},
        {32'hFFFFFFFF},
        {32'hFFFFFFFF},
        {32'hFFFFFFFF},
        {32'hFFFFFFFF},
        {32'hFFFFFFFF},
        {32'hFFFFFFFF},
        {32'hFFFFFFFF},
        {32'hFFFFFFFF},
        {32'hFFFFFFFF},
        {32'hFFFFFFFF},
        {32'hFFFFFFFF},
        {32'hFFFFFFFF},
        {32'hFFFFFFFF},
        {32'hFFFFFFFF},
        {32'hFFFFFFFF},
        {32'hFFFFFFFF},
        {32'hFFFFFFFF},
        {32'hFFFFFFFF},
        {32'hFFFFFFFF},
        {32'hFFFFFFFF},
        {32'hFFFFFFFF},
        {32'hFFFFFFFF},
        {32'hFFFFFFFF},
        {32'hFFFFFFFF},
        {32'hFFFFFFFF},
        {32'hFFFFFFFF},
        {32'hFFFFFFFF},
        {32'hFFFFFFFF},
        {32'hFFFFFFFF},
        {32'hFFFFFFFF},
        {32'hFFFFFFFF},
        {32'hFFFFFFFF},
        {32'hFFFFFFFF},
        {32'hFFFFFFFF},
        {32'hFFFFFFFF},
        {32'hFFFFFFFF},
        {32'hFFFFFFFF},
        {32'hFFFFFFFF},
        {32'hFFFFFFFF},
        {32'hFFFFFFFF},
        {32'hFFFFFFFF},
        {32'hFFFFFFFF},
        {32'hFFFFFFFF},
        {32'hFFFFFFFF},
        {32'hFFFFFFFF},
        {32'hFFFFFFFF},
        {32'hFFFFFFFF},
        {32'hFFFFFFFF},
        {32'hFFFFFFFF},
        {32'hFFFFFFFF},
        {32'hFFFFFFFF},
        {32'hFFFFFFFF},
        {32'hFFFFFFFF},
        {32'hFFFFFFFF},
        {32'hFFFFFFFF},
        {32'hFFFFFFFF},
        {32'hFFFFFFFF},
        {32'hFFFFFFFF},
        {_sevenSegDisplay_slot_io_rd_data},
        {_timer_slot_io_rd_data},
        {_gpi_slot_io_rd_data},
        {_gpo_slot_io_rd_data}}),
    .io_slot_read       (_mmioController_io_slot_read)
  );
  GPO gpo (
    .clock           (clock),
    .reset           (reset),
    .slot_io_address (_mmioController_io_slot_reg_addr[6'h0]),
    .slot_io_rd_data (_gpo_slot_io_rd_data),
    .slot_io_wr_data (_mmioController_io_slot_write_data[6'h0]),
    .slot_io_read    (_mmioController_io_slot_read[0]),
    .slot_io_write   (_mmioController_io_slot_write[0]),
    .slot_io_cs      (_mmioController_io_slot_cs[0]),
    .io              (_gpo_io)
  );
  GPI gpi (
    .clock           (clock),
    .reset           (reset),
    .slot_io_address (_mmioController_io_slot_reg_addr[6'h1]),
    .slot_io_rd_data (_gpi_slot_io_rd_data),
    .slot_io_wr_data (_mmioController_io_slot_write_data[6'h1]),
    .slot_io_read    (_mmioController_io_slot_read[1]),
    .slot_io_write   (_mmioController_io_slot_write[1]),
    .slot_io_cs      (_mmioController_io_slot_cs[1]),
    .io_data_in      (io_data_in)
  );
  timer timer (
    .clock           (clock),
    .reset           (reset),
    .slot_io_address (_mmioController_io_slot_reg_addr[6'h2]),
    .slot_io_rd_data (_timer_slot_io_rd_data),
    .slot_io_wr_data (_mmioController_io_slot_write_data[6'h2]),
    .slot_io_read    (_mmioController_io_slot_read[2]),
    .slot_io_write   (_mmioController_io_slot_write[2]),
    .slot_io_cs      (_mmioController_io_slot_cs[2])
  );
  SevSegDisplay_core sevenSegDisplay (
    .clock           (clock),
    .reset           (reset),
    .slot_io_address (_mmioController_io_slot_reg_addr[6'h3]),
    .slot_io_rd_data (_sevenSegDisplay_slot_io_rd_data),
    .slot_io_wr_data (_mmioController_io_slot_write_data[6'h3]),
    .slot_io_read    (_mmioController_io_slot_read[3]),
    .slot_io_write   (_mmioController_io_slot_write[3]),
    .slot_io_cs      (_mmioController_io_slot_cs[3]),
    .io              (_sevenSegDisplay_io)
  );
  assign io_data_out = _gpo_io.data_out;
  assign io_anode_assert = _sevenSegDisplay_io.anode_select;
  assign io_segs = _sevenSegDisplay_io.segs;
endmodule

