// Generated by CIRCT firtool-1.62.1
module Top(
  input         clock,
                reset,
  input  [15:0] sw,
  output [15:0] led,
  output [7:0]  anode_assert,
  output [6:0]  segs
);

  main m (
    .clock        (clock),
    .reset        (reset),
    .sw           (sw),
    .led          (led),
    .anode_assert (anode_assert),
    .segs         (segs)
  );
endmodule

